### ISSUE TITLE
Day 1: works like a charm, Day 2: Timeouts - Salesforce Penalities?

### ISSUE THREAD

**Issue by rsoesemann** [JenniferSimonds/apex-xpath#6]
I discovered your awesome lib while looking for a way to parse a 1 MB Metadata API WSDL in Apex. I made it work and it was lightning fast. But today I just get timeouts in my scratch org.

```
HttpRequest request = new HttpRequest();
request.setEndpoint(URL.getOrgDomainUrl().toExternalForm() + '/services/wsdl/metadata');
request.setMethod('GET');
request.setHeader('Cookie','sid=' + UserInfo.getSessionId());
request.setHeader('Content-Type', 'application/xml');

Blob wsdl = new Http().send(request).getBodyAsBlob();
XPath schema = new XPath( wsdl.toString() );

System.debug( SCHEMA.find('/definitions/types/xsd:schema/xsd:complexType').size() );
```

Also asked a question on StackExchange https://salesforce.stackexchange.com/q/353924/256

**Comment by rsoesemann** [comment]
Was related to my org always doing FINEST logging.

**Comment by JenniferSimonds** [comment]
Ah, thanks for the update! I was wracking my brain trying to think of how this could be happening & how to troubleshoot it.
